### ISSUE TITLE
Ability to set cover photo from a given url?

### ISSUE THREAD

**Issue by ajtatum** [joshuaavalon/AvalonRestAgent.bundle#1]
Hi Joshua! I've built an API to use your agent and loving it! However, it would be awesome if I could specify the cover photo of items via a URL. How would you recommend making those changes?

Thank you,
AJ

**Comment by joshuaavalon** [comment]
If you have not read the [PDF](https://github.com/joshuaavalon/AvalonRestAgent.bundle/files/2824168/plex.pdf), you should read it.

You need to set `metadata.poster`. Here is an example:

https://github.com/plexinc-agents/TheMovieDB.bundle/blob/64bf09b8a912c9751599e0c78d006e8cf115189b/Contents/Code/__init__.py#L717

You should also checkout [other agents](https://github.com/plexinc-agents) to see how they implement it.

**Comment by ajtatum** [comment]
Thanks Joshua for pointing me in the right direction! I've taken a couple stabs but have ended up posting the question on [StackOverflow](https://stackoverflow.com/questions/54546681/unable-to-set-plex-posters-metadata) to see what I'm doing wrong.
